trigger:
  tags:
    include:
      - "*"
resources:
  containers:
    - container: Java
      image: maven:3.9.1

pool: docker-new

variables:
  - group: sdk-release-variables

stages:
  - stage: Deploy
    jobs:
      - job: deploy_to_azure_artifacts
        container: Java
        steps:
          # Always attempt deployment
          - script: mvn deploy -s settings.xml
            displayName: "Maven Deploy"
            env:
              AZURE_PAT: $(AZURE_PAT)

          # Move to Release view only if tag trigger
          - script: |
              echo "Attempting to move package to Release view..."
              VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
              PATCH_URL="https://pkgs.dev.azure.com/GoFynd/JCPLibraries/_apis/packaging/feeds/fdk-client-java/maven/groups/com.azure.gofynd/artifacts/fdk-client-java/versions/$VERSION?api-version=7.1-preview.1"
              
              curl -s -w "\nHTTP Code: %{http_code}\n" -u ":$(AZURE_PAT)" -X PATCH \
                -H "Content-Type: application/json" \
                -d '{"views": {"op": "add", "path": "/views/-", "value": "release"}}' "$PATCH_URL"
            displayName: "Promote to Release View"
            env:
              AZURE_PAT: $(AZURE_PAT)